### ISSUE TITLE
Workaround to resolve fixed array dimensions being part of connect statements

### ISSUE THREAD

**Issue by tbeu** [oestersoetebier/IdealizedContact#25]
SimulationX has problems with connects of array components. I know this is rather embarrassing and a tool issue anyway. But since the dimensions are fixed and low in number this can be circumvented by explicitly resolving the arrays like I started in tbeu/IdealizedContact@8a14a925d7767deb6c5060a1f68269c075ddd3ba for CylinderToRectangle. Are you interested in such a workaround? If yes I'll try to resolve the other dimensions, too. If no I'll skip this.

**Comment by oestersoetebier** [comment]
At first, thank you very much for your input!
To be honest, I'd rather keep the array components. Maybe I could live with the workaround in case of the linear contacts because its only an array of 2. But when it comes to planar ones its 4 and there may be more in the future. So things will probably get messy with all the different blocks and connections. Do you know if this is a known issue in SimulationX? Are they working on it?
I will think this through but since I'm quite occupied at the moment it might take some time.

Unfortunately I was not able to test the library with SimulationX yet. Did it work after you removed the arrays?

**Comment by tbeu** [comment]
Yes, its is a know bug I reported a few years ago. Certainly it will be fixed some day but cannot tell when.
Example1, Example2, Example3 and Example4 work as expected. It's okay for me if you don't like the workaround. I just tried to get Example5 running somehow. After my commit tbeu/IdealizedContact@8a14a925d7767deb6c5060a1f68269c075ddd3ba the translation process of Example5 no longer fails but it does not initialize.
